title: Amir's Homepage
logo: /img/amir.png
description: ""
show_downloads: false

email       : amir.h.hadian@gmail.com

github:
  is_project_page: false
  
theme: jekyll-theme-minimal

attribution: false
